#LOWER LEARNING RATE WITH HIGHER BATCH SIZE
device: cpu
timeout: 1200

physics: 
  refresh_rate: 0.05 # This is in ms 10hz
  mass: 2 # kg
  g: 9.81 # Gravity Constant
  I_xx: 0.02166666666666667
  I_xy: 0.0
  I_xz: 0.0
  I_yx: 0.0
  I_yy: 0.02166666666666667
  I_yz: 0.0
  I_zx: 0.0
  I_zy: 0.0
  I_zz: 0.04000000000000001

normalization:
  norm: False
  velo_min: -10
  velo_max: 10
  euler_min: -1.0
  euler_max: 1.0
  omega_min: -0.785
  omega_max: 0.785
  act_min: 150
  act_max: 1000
  fxy_min: -38
  fxy_max: 38
  fz_min: -50
  fz_max: 50
  mxy_min: -4.64
  mxy_max: 4.64
  mz_min: -0.36
  mz_max: 0.36

replay_buffer:
  capacity: 10000
  start_learning: 1000

force_model:
  hidden_layers: 2
  hidden_size: 256
  output_dim: 6
  input_dim: 13
  state_dim: 12
  action_dim: 4
  activation: relu

training: 
  num_epochs: 64
  batch_size: 128
  lr: 0.0001
  min_lr: 0.0075
  init_seq_len: 2
  max_seq_len: 2
  seq_patience: 64
  seq_sch_thresh: 0.01
  loss_scaler: 1280
  beta: 0.2
  weight_decay: 0.0
  cos_lr: False

behavior:  
  horizon: 75 # 0.75 seconds with 0.01 refresh rate